motion:
  # Detection sensitivity threshold. Lower values indicate higher sensitivity.
  mse_threshold: 7
  # Duration in seconds. If no motion is detected within this time, 
  # the current recording is stopped.
  motion_gap: 2

recording:
  # Directory where recordings are saved.
  directory: "recordings"
  # Bitrate at which recordings are saved, in bits per second.
  bitrate: 1000000