motion:
  # Detection sensitivity threshold. Lower values indicate higher sensitivity.
  mse_threshold: 7
  # Duration in seconds. If no motion is detected within this time, 
  # the current recording is stopped.
  motion_gap: 10

capture:
  # Directory where captures are saved.
  directory: "captures"
  # Bitrate at which video captures are saved, in bits per second.
  bitrate: 1000000

notification:
  app_start:
    webhook_url: http://127.0.0.1:1880/api/app_start
  detection_start:
    webhook_url: http://127.0.0.1:1880/api/detection_start
  detection_end:
    webhook_url: http://127.0.0.1:1880/api/detection_end
  motion_start:
    webhook_url: http://127.0.0.1:1880/api/motion_start
  motion_end:
    webhook_url: http://127.0.0.1:1880/api/motion_end