# Logging settings
logging:

  # Logging level (Optional, Default: info)
  # Possible values: debug, info, warning, error, critical
  level: info

# Motion detection settings
motion:

  # Detection sensitivity threshold. Lower values indicate higher sensitivity (Required)
  mse_threshold: 7

  # Duration in seconds. If no motion is detected within this time, 
  # the current recording is stopped. (Required)
  motion_gap: 10

# Capture settings
capture:

  # Capture directory (Required)
  directory: captures
  
   # Resolution (Width x Height) for recorded videos. (Optional, Default [1024, 720])
  record_size: [1024, 720]

  # Resolution (Width x Height) used for motion detection, typically lower to save processing power.
  # (Optional, Default [320,240])
  detect_size: [320, 240]

  # Raw bitrate (Required)
  bitrate: 1000000

  # Output format for videos (Optional, Default: mp4)
  # Possible values: mp4, raw
  video_format: mp4

  # Maximum total size of the capture directory in MB (Optional, Default: 20480)
  max_size_mb: 20480

  # Maximum age of files in the capture directory in days (Optional, Default: 7)
  max_age_days: 7

# Notification Settings
notification:

  # Triggered when the application starts
  application_started:
    webhook_url: "http://127.0.0.1:1880/api/application_started"

  # Triggered when motion detection is enabled
  detection_enabled:
    webhook_url: "http://127.0.0.1:1880/api/detection_enabled"

  # Triggered when motion detection is disabled
  detection_disabled:
    webhook_url: "http://127.0.0.1:1880/api/detection_disabled"

  # Triggered when motion is detected and recording starts
  motion_started:
    webhook_url: "http://127.0.0.1:1880/api/motion_started"

  # Triggered when motion stops, and recording ends
  motion_stopped:
    webhook_url: "http://127.0.0.1:1880/api/motion_stopped"
