# Logging settings
# logging:

  # Logging level (Optional, Default: info)
  # Possible values: debug, info, warning, error, critical
  # level: info

# Motion detection settings
# motion:

  # Detection sensitivity threshold. Lower values indicate higher sensitivity (Optional, Default 7)
  # mse_threshold: 7

  # Duration in seconds. If no motion is detected within this time, 
  # the current recording is stopped. (Optional, Default 10)
  # motion_gap: 10

  # Maximum clip length in seconds. If set to 0 or None, this has no effect. 
  # (Optional, Default: None)
  # max_clip_length: None

  # Minimum clip length in seconds. If set to 0 or None, this has no effect. 
  # (Optional, Default: None)
  # min_clip_length: None


# Capture settings
# capture:

  # Capture directory (Optional, Default captures)
  # directory: captures
  
   # Resolution (Width x Height) for recorded videos. (Optional, Default [1024, 720])
  # record_size: [1024, 720]

  # Resolution (Width x Height) used for motion detection, typically lower to save processing power.
  # (Optional, Default [320,240])
  # detect_size: [320, 240]

  # Raw bitrate (Optional, Default 1000000)
  # bitrate: 1000000

  # Framerate per second (Optional, Default 30)
  # framerate: 30

  # Tuning file to be use to calibrate common RPi cameras. (Optional, Default None)
  # List of possible values can be found at: https://github.com/raspberrypi/libcamera/tree/main/src/ipa/rpi/vc4/data
  # tuning: imx477_noir

  # Output format for videos (Optional, Default: mp4)
  # Possible values: mp4, h264
  # video_format: mp4

  # Maximum total size of the capture directory in MB (Optional, Default: None)
  # max_size_mb: 20480

  # Maximum age of files in the capture directory in days (Optional, Default: None)
  # max_age_days: 7

# Notification Settings (Optional)
# notification:

  # Triggered when the application starts
  # application_started:
  #   webhook_url: "http://127.0.0.1:1880/api/application_started"

  # Triggered when motion detection is enabled
  # detection_enabled:
  #   webhook_url: "http://127.0.0.1:1880/api/detection_enabled"

  # Triggered when motion detection is disabled
  # detection_disabled:
  #   webhook_url: "http://127.0.0.1:1880/api/detection_disabled"

  # Triggered when motion is detected and recording starts
  # motion_started:
  #   webhook_url: "http://127.0.0.1:1880/api/motion_started"

  # Triggered when motion stops, and recording ends
  # motion_stopped:
  #   webhook_url: "http://127.0.0.1:1880/api/motion_stopped"
